// Code generated by goctl. DO NOT EDIT.
// Source: favorite.proto

package favoriteservice

import (
	"context"

	"tiktok-micro/app/services/favorite/favorite_pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	FavoriteActionRequest  = favorite_pb.FavoriteActionRequest
	FavoriteActionResponse = favorite_pb.FavoriteActionResponse
	FavoriteListRequest    = favorite_pb.FavoriteListRequest
	FavoriteListResponse   = favorite_pb.FavoriteListResponse
	UserInfo               = favorite_pb.UserInfo
	VideoInfo              = favorite_pb.VideoInfo

	FavoriteService interface {
		FavoriteAction(ctx context.Context, in *FavoriteActionRequest, opts ...grpc.CallOption) (*FavoriteActionResponse, error)
		FavoriteList(ctx context.Context, in *FavoriteListRequest, opts ...grpc.CallOption) (*FavoriteListResponse, error)
	}

	defaultFavoriteService struct {
		cli zrpc.Client
	}
)

func NewFavoriteService(cli zrpc.Client) FavoriteService {
	return &defaultFavoriteService{
		cli: cli,
	}
}

func (m *defaultFavoriteService) FavoriteAction(ctx context.Context, in *FavoriteActionRequest, opts ...grpc.CallOption) (*FavoriteActionResponse, error) {
	client := favorite_pb.NewFavoriteServiceClient(m.cli.Conn())
	return client.FavoriteAction(ctx, in, opts...)
}

func (m *defaultFavoriteService) FavoriteList(ctx context.Context, in *FavoriteListRequest, opts ...grpc.CallOption) (*FavoriteListResponse, error) {
	client := favorite_pb.NewFavoriteServiceClient(m.cli.Conn())
	return client.FavoriteList(ctx, in, opts...)
}
