// Code generated by goctl. DO NOT EDIT.
// Source: messages.proto

package messageservice

import (
	"context"

	"tiktok-micro/app/services/message/messages_pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	MessageActionRequest  = messages_pb.MessageActionRequest
	MessageActionResponse = messages_pb.MessageActionResponse
	MessageInfo           = messages_pb.MessageInfo
	MessageListRequest    = messages_pb.MessageListRequest
	MessageListResponse   = messages_pb.MessageListResponse

	MessageService interface {
		MessageAction(ctx context.Context, in *MessageActionRequest, opts ...grpc.CallOption) (*MessageActionResponse, error)
		GetMessageList(ctx context.Context, in *MessageListRequest, opts ...grpc.CallOption) (*MessageListResponse, error)
	}

	defaultMessageService struct {
		cli zrpc.Client
	}
)

func NewMessageService(cli zrpc.Client) MessageService {
	return &defaultMessageService{
		cli: cli,
	}
}

func (m *defaultMessageService) MessageAction(ctx context.Context, in *MessageActionRequest, opts ...grpc.CallOption) (*MessageActionResponse, error) {
	client := messages_pb.NewMessageServiceClient(m.cli.Conn())
	return client.MessageAction(ctx, in, opts...)
}

func (m *defaultMessageService) GetMessageList(ctx context.Context, in *MessageListRequest, opts ...grpc.CallOption) (*MessageListResponse, error) {
	client := messages_pb.NewMessageServiceClient(m.cli.Conn())
	return client.GetMessageList(ctx, in, opts...)
}
