// Code generated by goctl. DO NOT EDIT.
// Source: favorite.proto

package server

import (
	"context"

	"tiktok-micro/app/services/favorite/favorite_pb"
	"tiktok-micro/app/services/favorite/internal/logic"
	"tiktok-micro/app/services/favorite/internal/svc"
)

type FavoriteServiceServer struct {
	svcCtx *svc.ServiceContext
	favorite_pb.UnimplementedFavoriteServiceServer
}

func NewFavoriteServiceServer(svcCtx *svc.ServiceContext) *FavoriteServiceServer {
	return &FavoriteServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *FavoriteServiceServer) FavoriteAction(ctx context.Context, in *favorite_pb.FavoriteActionRequest) (*favorite_pb.FavoriteActionResponse, error) {
	l := logic.NewFavoriteActionLogic(ctx, s.svcCtx)
	return l.FavoriteAction(in)
}

func (s *FavoriteServiceServer) FavoriteList(ctx context.Context, in *favorite_pb.FavoriteListRequest) (*favorite_pb.FavoriteListResponse, error) {
	l := logic.NewFavoriteListLogic(ctx, s.svcCtx)
	return l.FavoriteList(in)
}
