// Code generated by goctl. DO NOT EDIT.
// Source: video.proto

package server

import (
	"context"

	"tiktok-micro/app/services/video/internal/logic"
	"tiktok-micro/app/services/video/internal/svc"
	"tiktok-micro/app/services/video/video_pb"
)

type VideoServiceServer struct {
	svcCtx *svc.ServiceContext
	video_pb.UnimplementedVideoServiceServer
}

func NewVideoServiceServer(svcCtx *svc.ServiceContext) *VideoServiceServer {
	return &VideoServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *VideoServiceServer) UploadVideo(ctx context.Context, in *video_pb.UploadVideoRequest) (*video_pb.UploadVideoResponse, error) {
	l := logic.NewUploadVideoLogic(ctx, s.svcCtx)
	return l.UploadVideo(in)
}

func (s *VideoServiceServer) PublishList(ctx context.Context, in *video_pb.PublishlistRequest) (*video_pb.PublishlistResponse, error) {
	l := logic.NewPublishListLogic(ctx, s.svcCtx)
	return l.PublishList(in)
}

func (s *VideoServiceServer) GetVideoInfo(ctx context.Context, in *video_pb.GetVideoInfoRequest) (*video_pb.GetVideoInfoResponse, error) {
	l := logic.NewGetVideoInfoLogic(ctx, s.svcCtx)
	return l.GetVideoInfo(in)
}
