// Code generated by goctl. DO NOT EDIT.
// Source: feed.proto

package server

import (
	"context"

	"tiktok-micro/app/services/feed/feed_pb"
	"tiktok-micro/app/services/feed/internal/logic"
	"tiktok-micro/app/services/feed/internal/svc"
)

type FeedServiceServer struct {
	svcCtx *svc.ServiceContext
	feed_pb.UnimplementedFeedServiceServer
}

func NewFeedServiceServer(svcCtx *svc.ServiceContext) *FeedServiceServer {
	return &FeedServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *FeedServiceServer) FeedList(ctx context.Context, in *feed_pb.FeedRequest) (*feed_pb.FeedResponse, error) {
	l := logic.NewFeedListLogic(ctx, s.svcCtx)
	return l.FeedList(in)
}
