// Code generated by goctl. DO NOT EDIT.
// Source: relation.proto

package server

import (
	"context"

	"tiktok-micro/app/services/relation/internal/logic"
	"tiktok-micro/app/services/relation/internal/svc"
	"tiktok-micro/app/services/relation/relation_pb"
)

type RelationServiceServer struct {
	svcCtx *svc.ServiceContext
	relation_pb.UnimplementedRelationServiceServer
}

func NewRelationServiceServer(svcCtx *svc.ServiceContext) *RelationServiceServer {
	return &RelationServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *RelationServiceServer) RelationAction(ctx context.Context, in *relation_pb.RelationActionRequest) (*relation_pb.RelationActionResponse, error) {
	l := logic.NewRelationActionLogic(ctx, s.svcCtx)
	return l.RelationAction(in)
}

func (s *RelationServiceServer) GetFollowList(ctx context.Context, in *relation_pb.GetFollowListRequest) (*relation_pb.GetFollowListResponse, error) {
	l := logic.NewGetFollowListLogic(ctx, s.svcCtx)
	return l.GetFollowList(in)
}

func (s *RelationServiceServer) GetFansList(ctx context.Context, in *relation_pb.GetFansListRequest) (*relation_pb.GetFansListResponse, error) {
	l := logic.NewGetFansListLogic(ctx, s.svcCtx)
	return l.GetFansList(in)
}

func (s *RelationServiceServer) GetFriendList(ctx context.Context, in *relation_pb.GetFriendListRequest) (*relation_pb.GetFriendListResponse, error) {
	l := logic.NewGetFriendListLogic(ctx, s.svcCtx)
	return l.GetFriendList(in)
}
