// Code generated by goctl. DO NOT EDIT.
// Source: feed.proto

package feedservice

import (
	"context"

	"tiktok-micro/app/services/feed/feed_pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	FeedRequest  = feed_pb.FeedRequest
	FeedResponse = feed_pb.FeedResponse
	UserInfo     = feed_pb.UserInfo
	VideoInfo    = feed_pb.VideoInfo

	FeedService interface {
		FeedList(ctx context.Context, in *FeedRequest, opts ...grpc.CallOption) (*FeedResponse, error)
	}

	defaultFeedService struct {
		cli zrpc.Client
	}
)

func NewFeedService(cli zrpc.Client) FeedService {
	return &defaultFeedService{
		cli: cli,
	}
}

func (m *defaultFeedService) FeedList(ctx context.Context, in *FeedRequest, opts ...grpc.CallOption) (*FeedResponse, error) {
	client := feed_pb.NewFeedServiceClient(m.cli.Conn())
	return client.FeedList(ctx, in, opts...)
}
